---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: always
    image: spritsail/docker-build

  - name: publish-spritsail
    pull: always
    image: registry.spritsail.io/spritsail/docker-publish
    settings:
      registry: registry.spritsail.io
      login: { from_secret: spritsail_login }
      repo: spritsail/roc
      tags:
        - latest
        - "%label org.label-schema.version"
      delete: no # so we can push to dockerhub+ghcr
    depends_on:
      - build
    when:
      branch:
        - master
      event:
        - push

  - name: publish-ghcr
    pull: never
    image: registry.spritsail.io/spritsail/docker-publish
    settings:
      registry: ghcr.io
      login: { from_secret: ghcr_login }
      repo: spritsail/roc
      tags:
        - latest
        - "%label org.label-schema.version"
      delete: no # so we can push to dockerhub
    depends_on:
      - build
    when:
      branch:
        - master
      event:
        - push

  - name: publish-dockerhub
    pull: never
    image: registry.spritsail.io/spritsail/docker-publish
    settings:
      login: { from_secret: docker_login }
      repo: spritsail/roc
      tags:
        - latest
        - "%label org.label-schema.version"
    depends_on:
      - build
    when:
      branch:
        - master
      event:
        - push

---
kind: pipeline
name: update-readme

steps:
  - name: dockerhub-readme
    pull: always
    image: jlesage/drone-push-readme
    settings:
      username: { from_secret: docker_username }
      password: { from_secret: docker_password }
      repo: spritsail/roc
    when:
      branch:
        - master
      event:
        - push
---
kind: signature
hmac: 9ced2c55eb61f4c0c21aeae79a89188847f296027825cc3c2e5c66d7957aee69

...
